[package]
name = "fuxi-quant-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
hf-hub = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }
tokenizers = { workspace = true }
serde_json = { workspace = true }
